---
name: Checks

on: [push] #Trigger

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-latest #ubuntu-20.44 - không chạy
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"